apiVersion: v1
kind: Service
metadata:
  name: coworking-checkin-api
spec:
  selector:
    app.kubernetes.io/name: coworking-checkin-api
  ports:
  - name: "5151"
    protocol: TCP
    port: 5151
    targetPort: 5151
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-checkin-api
  labels:
    name: coworking-checkin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking-checkin-api
  template:
    metadata:
      labels:
        service: coworking-checkin-api
    spec:
      containers:
      - name: coworking-checkin-api
        image: 432255178055.dkr.ecr.us-east-1.amazonaws.com/coworking-checkin:latest
        # image: localhost:5000/my-image
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5151
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5151
          initialDelaySeconds: 5
          timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME    
      restartPolicy: Always